### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by Ti-webdev** [zenato/docker-puppeteer#1]
I got an error: Failed to connect to chrome

**Comment by Ti-webdev** [comment]
Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

It's work fine:
```js
const browser = await puppeteer.launch({
  args: ['--no-sandbox']
});
```

or run as node user:
`docker run --user node...`

**Comment by zenato** [comment]
@Ti-webdev Thanks for your answer.

see extra project [pupeteer-renderer](https://github.com/zenato/puppeteer-renderer)
