### ISSUE TITLE
How did you end up with this list of dependencies?

### ISSUE THREAD

**Issue by gajus** [zenato/docker-puppeteer#2]
This looks like a rather excessive list of dependencies,

https://github.com/zenato/docker-puppeteer/blob/52797f3a3b8503af398e7547de778e47810293a2/Dockerfile#L5-L45

How did you get to this list?

**Comment by zenato** [comment]
These are the libraries you need to run chromium.
Please let me know if you find anything it doesn't need.

**Comment by gajus** [comment]
> These are the libraries you need to run chromium.

Right... but where did you get that list from?

Is there an official reference?

**Comment by zenato** [comment]
I don't know if there is an official document.
I tried to refer to other docker images and blogs, but I don't know the source URL.
If you have any idea, please send a pull request.
:)

**Comment by gajus** [comment]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch
