### ISSUE TITLE
Warning: apt-key output should not be parsed (stdout is not a terminal)

### ISSUE THREAD

**Issue by lodge-seven** [zenato/docker-puppeteer#4]
Please tell me how to solve this problem

**Comment by zenato** [comment]
@lodge-seven Can you show me how to use this image?
I tried below, It works fine.

```sh
docker run -i --rm --cap-add=SYS_ADMIN --name test zenato/puppeteer node -e "`cat test.js`"
```

**Comment by movd** [comment]
This appears when building the Image with the Dockerfile.  Setting `ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1` fixes this. 

Reference: https://stackoverflow.com/questions/48162574/how-to-circumvent-apt-key-output-should-not-be-parsed
